### PR TITLE
Fix Duke photo, modify form styling to accomodate

### PR DESCRIPTION
**Pull request by jameswmoody**

### CODE REVIEW

**Review by nicoglennon — CHANGES_REQUESTED** [review]
None of the AJAX functionality from the last merge is working on this branch - I think you got rid of a few divs and changed a few classes that seemed unnecessary at first sight. But those actually were there in order to traverse the DOM and append forms/comments with JS.
Do you think you can fix the question form & Duke's photo without changing those, or is it necessary to redo the JS?

**Comment by nicoglennon** [comment]
Haha sorry, did not know that the "Request change" option looked this menacing

**Comment by jameswmoody** [comment]
@nicoglennon I noticed that too but I think I noticed it before I had any changes. I'll revert on my machine and see, something could have gotten messed up from my pull to master before I strated working

**Comment by jameswmoody** [comment]
@nicoglennon yeah its working fine on my master branch which doesn't have the changes in this PR so I must have broke it haha. I'll revise so that it won't override anything

**Comment by jameswmoody** [comment]
@nicoglennon ok I see what happened. From looking at the 'files changed' section it looks like parts of the comment form were modified in this PR but I didn't change while fixing the photo layout. I think it came from when I pulled to master, some stuff didnt merge properly on my end. anyway, I'm working on this and looking at ajax-ing the vote logic

**Comment by nicoglennon** [comment]
Yes, I saw that the div with class="comments-only" around the comment boxes was deleted, and the 'Comments' a-tag that opens the comment form was moved outside of the div with class="comment-div". Some classes like the "open-comment-form" in that 'Comments' a-tag are gone too.

No worries - It's not something I would've thought about either. There are a lot of dependencies between the HTML/CSS and the JS... Hard to change anything at this point without having side effects.

I'll look at what else I can AJAXify (questions, answers).

**Pull request closed without merging**
